# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Delight Travel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Delight Travel

pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'FirebaseAuth'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'IQKeyboardManagerSwift'
pod 'MBProgressHUD', '~> 1.2.0'
pod 'CodableFirebase'
pod 'AlamofireImage'

end
